---
- name: Get kuber credentials
  hosts: master
  become: yes
  gather_facts: yes
  tasks:
    - name: Save host to var
      set_fact:
        master: "{{ ansible_host }}"
    - name: Print fact
      debug:
        var: master

    - name: Duplicate folder kube
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /etc/kubernetes/admin_export.conf
        remote_src: yes
        mode: 0755

    - name: Set Kube IP in config
      replace:
        path: /etc/kubernetes/admin_export.conf
        regexp: "server: https://[0-9.]*:"
        replace: "server: https://{{ master }}:"
    - name: Fetch kube config
      synchronize:
        src: /etc/kubernetes/admin_export.conf
        dest: ../kubeconfig/kubeconfig
        delete: yes
        recursive: yes
        owner: no
        group: no
        mode: pull